input UserInfo {
  code: String!
  firstName: String!
  lastName: String!
  email: String!
  phone: String!
}

type Token {
  token: String!
}

type Query {
  checkCode(code: String!): Boolean!
}

type Mutation {
  login(userInfo: UserInfo!): Token!
}
